blank_issues_enabled: false
contact_links:
  - name: Support
    about: Please ask and answer questions here
  - name: List a token
    url: https://github.com/Kimciswap/default-token-list#adding-a-token
    about: Any requests to add a token to KSWAP should go here
